PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/CoctelController.cs
using Microsoft.AspNetCore.Mvc;
using ML;

namespace PL.Controllers
{
    public class CoctelController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Coctel coctel = new ML.Coctel();
            coctel.Cocteles = new List<object>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/");

                var responseTask = client.GetAsync("json/v1/1/search.php?s=");
                responseTask.Wait();

                var resultUsuario = responseTask.Result;

                if (resultUsuario.IsSuccessStatusCode)
                {
                    var readTask = resultUsuario.Content.ReadAsAsync<dynamic>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.drinks)
                    {
                        ML.Coctel resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Coctel>(resultItem.ToString());

                        coctel.Cocteles.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }

            }
            return View(coctel);

        }


        [HttpPost]
        public ActionResult GetAll(ML.Coctel coctel)
        {
            coctel.Cocteles = new List<object>();
            if (coctel.Ingrediente == null && coctel.strDrink == null)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/");

                    var responseTask = client.GetAsync("json/v1/1/search.php?s=");
                    responseTask.Wait();

                    var resultUsuario = responseTask.Result;

                    if (resultUsuario.IsSuccessStatusCode)
                    {
                        var readTask = resultUsuario.Content.ReadAsAsync<dynamic>();
                        readTask.Wait();

                        foreach (var resultItem in readTask.Result.drinks)
                        {
                            ML.Coctel resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Coctel>(resultItem.ToString());

                            coctel.Cocteles.Add(resultItemList);
                        }
                    }
                }
            }
            else
            {
                if (coctel.strDrink != null)
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/");

                        var responseTask = client.GetAsync("json/v1/1/search.php?s=" + coctel.strDrink);
                        responseTask.Wait();

                        var resultUsuario = responseTask.Result;

                        if (resultUsuario.IsSuccessStatusCode)
                        {
                            var readTask = resultUsuario.Content.ReadAsAsync<dynamic>();
                            readTask.Wait();

                            foreach (var resultItem in readTask.Result.drinks)
                            {
                                ML.Coctel resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Coctel>(resultItem.ToString());

                                coctel.Cocteles.Add(resultItemList);
                            }
                        }
                        else
                        {
                            ViewBag.Message = "Ocurrio un error al hacer la consulta";
                            return View("Modal");
                        }

                    }

                }
                else
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/");

                        var responseTask = client.GetAsync("json/v1/1/filter.php?i=" + coctel.Ingrediente);
                        responseTask.Wait();

                        var resultUsuario = responseTask.Result;

                        if (resultUsuario.IsSuccessStatusCode)
                        {
                            var readTask = resultUsuario.Content.ReadAsAsync<dynamic>();
                            readTask.Wait();

                            foreach (var resultItem in readTask.Result.drinks)
                            {
                                ML.Coctel resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Coctel>(resultItem.ToString());

                                coctel.Cocteles.Add(resultItemList);
                            }
                        }
                        else
                        {
                            ViewBag.Message = "Ocurrio un error al hacer la consulta";
                            return View("Modal");
                        }

                    }
                }
            }
            
            return View(coctel);

        }
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Views/Coctel/GetAll.cshtml
@model ML.Coctel
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class=row>
        <div class="text-center">
            <h2>Cocteles</h2>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h5>Ingrese el coctel que desea buscar</h5>
            <hr />
        </div>
    </div>

</div>

<div class="col-md-12">
    @using (Html.BeginForm("GetAll", "Coctel", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
      
        <div class="row">

            <div class="col-md-3">

                <div class="input-group">
                    <span class="input-group-text">
                        <i class="fa-solid fa-circle-user"></i>
                    </span>
                    @Html.TextBoxFor(model => model.strDrink, new { @class = "form-control", @id = "txtNombre",@placeholder = "Nombre"})

                </div>
            </div>

            <div class="col-md-3">

                <div class="input-group">
                    <span class="input-group-text"><i class="fa-solid fa-circle-user"></i></span>
                    @Html.TextBoxFor(model => model.Ingrediente, new { @class = "form-control", @id = "txtApellidoPaterno", @placeholder = "Ingrediente" })
                </div>
            </div>

         
        </div>
        <br />
        <div class="container">

            <div class="col">
                <input type="submit" value="Buscar" class="btn btn-info" />

            </div>
        </div>
    }
</div>
<br />

<div class="row">
  
    @foreach (ML.Coctel coctel in Model.Cocteles)
    {
        <div class="col-md-3 mt-3 pt-3">
            <div class="card text-white bg-dark border-success mb-3 bor" style="width: 19rem; height: 50rem;">
                <p class="card-text" style="text-align: center; vertical-align: middle;"><img id="Img" src="@coctel.strDrinkThumb" style="width:250px ; height:250px" /></p>
                <h5 class="card-title" style="text-align: center; vertical-align: middle;">@coctel.strDrink </h5>
                @if (coctel.strIngredient1 != null)
                {
                    @if (coctel.strIngredient2 != null)
                    {
                        <p class="card-text" style="text-align: center; vertical-align: middle;">Ingredientes</p>
                        <p class="card-text" style="text-align: center; vertical-align: middle;">@coctel.strIngredient1 | @coctel.strIngredient2 </p>
                        <p class="card-text" style="text-align: center; vertical-align: middle;"><img id="Img" src="@coctel.URL@coctel.strIngredient1@coctel.extension" style="width:50px ; height:50px" /> <img id="Img" src="@coctel.URL@coctel.strIngredient2@coctel.extension" style="width:50px ; height:50px" /></p>
                    }
                }
                
         
                @if (coctel.strIngredient3 != null)
                {
                    @if (coctel.strIngredient4 != null)
                    {
                        <p class="card-text" style="text-align: center; vertical-align: middle;">@coctel.strIngredient3 | @coctel.strIngredient4</p>
                        <p class="card-text" style="text-align: center; vertical-align: middle;"><img id="Img" src="@coctel.URL@coctel.strIngredient3@coctel.extension" style="width:50px ; height:50px" /><img id="Img" src="@coctel.URL@coctel.strIngredient4@coctel.extension" style="width:50px ; height:50px" /></p>
                    }
                    else
                    {
                        <p class="card-text" style="text-align: center; vertical-align: middle;">@coctel.strIngredient3 </p>
                        <p class="card-text" style="text-align: center; vertical-align: middle;"><img id="Img" src="@coctel.URL@coctel.strIngredient3@coctel.extension" style="width:50px ; height:50px" /></p>

                    }
                }
               
                @if (coctel.strIngredient5 != null)
                {
                    @if(coctel.strIngredient6 !=null)
                    {
                            <p class="card-text" style="text-align: center; vertical-align: middle;">@coctel.strIngredient5 | @coctel.strIngredient6</p>
                            <p class="card-text" style="text-align: center; vertical-align: middle;"><img id="Img" src="@coctel.URL@coctel.strIngredient5@coctel.extension" style="width:50px ; height:50px" /><img id="Img" src="@coctel.URL@coctel.strIngredient6@coctel.extension" style="width:25px ; height:25px" /></p>
                     }
                        else
                        {


                            <p class="card-text" style="text-align: center; vertical-align: middle;">@coctel.strIngredient5 </p>
                            <p class="card-text" style="text-align: center; vertical-align: middle;"><img id="Img" src="@coctel.URL@coctel.strIngredient5@coctel.extension" style="width:50px ; height:50px" /></p>
                        }
                }
                @if(coctel.strInstructionsES != null){
                    <p class="card-text" style="text-align: center; vertical-align: middle;">Instrucciones</p>
                    <p class="card-text" style="text-align: center; vertical-align: middle;">@coctel.strInstructionsES</p>
                }
                else{
                    <p class="card-text" style="text-align: center; vertical-align: middle;">Instrucciones</p>
                    <p class="card-text" style="text-align: center; vertical-align: middle;">@coctel.strInstructions</p>
                }
               
              
            </div>
        </div>

    }

</div>

PL/Views/Coctel/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Coctel", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coctel" asp-action="GetAll">Cocteles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>